apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    business-unit: BU1
    compliance: NA
    component: rabbitmq
    confidentiality: private
    deployed-by: helm
    name: robot-shop
    owner: devteam
    profile-environment: non-prod-app-cluster
    project: robots
    tier: app
    version: "1.0"             
  name: rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        business-unit: BU1
        compliance: NA
        component: rabbitmq
        confidentiality: private
        deployed-by: helm
        name: robot-shop
        owner: devteam
        profile-environment: non-prod-app-cluster
        project: robots
        tier: app
        version: "1.0"              
    spec:
      containers:
      - image: rabbitmq:3.7-management-alpine
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always
status: {}
